-- ============================================================================
-- Fee reminder log — audit trail for every reminder attempt.
--
-- Records WHAT was sent, to WHOM, on WHICH channels, and whether each channel
-- actually delivered. Channels that are not configured (SMS / WhatsApp are not
-- wired to a provider yet) record as NOT delivered rather than silently
-- pretending — the screen shows the honest status.
--
-- Drives: the "Sent Today" KPI, the "Last" column on the defaulter list, and
-- the Recent Reminder History panel.
--
-- Target DB: PostgreSQL (educore). Safe to re-run.
-- ============================================================================

CREATE TABLE IF NOT EXISTS core.fee_reminder_log
(
    reminder_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          integer      NOT NULL,
    school_id          integer      NOT NULL,
    student_id         integer      NOT NULL,
    channels_requested varchar(60)  NOT NULL,            -- 'Email,Sms'
    channels_delivered varchar(60)  NOT NULL DEFAULT '', -- 'Email'  ('' = nothing delivered)
    to_email           varchar(150),
    to_phone           varchar(30),
    message            text,
    outstanding        numeric(12,2) NOT NULL DEFAULT 0, -- amount owed at send time
    status             varchar(20)  NOT NULL,            -- Sent | Partial | Failed
    sent_by            integer,
    sent_at            timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_fee_reminder_log_scope
    ON core.fee_reminder_log (tenant_id, school_id, sent_at DESC);
CREATE INDEX IF NOT EXISTS ix_fee_reminder_log_student
    ON core.fee_reminder_log (tenant_id, school_id, student_id, sent_at DESC);

-- ── Record one reminder attempt ─────────────────────────────────────────────
CREATE OR REPLACE PROCEDURE core.sp_fee_reminder_record(
    IN    p_tenant_id          integer,
    IN    p_school_id          integer,
    IN    p_action_user_id     integer,
    IN    p_student_id         integer,
    IN    p_channels_requested varchar,
    IN    p_channels_delivered varchar,
    IN    p_to_email           varchar,
    IN    p_to_phone           varchar,
    IN    p_message            text,
    IN    p_outstanding        numeric,
    IN    p_status             varchar,
    INOUT p_result             refcursor DEFAULT 'reminder_record_cursor'::refcursor
)
LANGUAGE plpgsql
AS $procedure$
DECLARE v_id integer;
BEGIN
    IF p_tenant_id <= 1 OR p_school_id <= 0 OR p_student_id <= 0 THEN
        RAISE EXCEPTION 'Invalid request.';
    END IF;

    INSERT INTO core.fee_reminder_log
        (tenant_id, school_id, student_id, channels_requested, channels_delivered,
         to_email, to_phone, message, outstanding, status, sent_by)
    VALUES
        (p_tenant_id, p_school_id, p_student_id,
         COALESCE(p_channels_requested, ''), COALESCE(p_channels_delivered, ''),
         NULLIF(TRIM(p_to_email), ''), NULLIF(TRIM(p_to_phone), ''),
         NULLIF(TRIM(p_message), ''), COALESCE(p_outstanding, 0),
         COALESCE(NULLIF(TRIM(p_status), ''), 'Failed'), p_action_user_id)
    RETURNING reminder_id INTO v_id;

    OPEN p_result FOR SELECT TRUE AS success, v_id AS reminder_id;
END;
$procedure$;

-- ── Recent history + today's count ──────────────────────────────────────────
-- Two cursors: the recent rows for the history panel, and a stats row for the
-- "Sent Today" KPI (counts reminders where at least one channel delivered).
CREATE OR REPLACE PROCEDURE core.sp_fee_reminder_history(
    IN    p_tenant_id      integer,
    IN    p_school_id      integer,
    IN    p_action_user_id integer,
    IN    p_take           integer   DEFAULT 10,
    INOUT p_rows           refcursor DEFAULT 'reminder_rows_cursor'::refcursor,
    INOUT p_stats          refcursor DEFAULT 'reminder_stats_cursor'::refcursor
)
LANGUAGE plpgsql
AS $procedure$
BEGIN
    IF p_tenant_id <= 1 OR p_school_id <= 0 THEN
        RAISE EXCEPTION 'Invalid school admin scope.';
    END IF;
    IF p_take IS NULL OR p_take < 1 THEN p_take := 10; END IF;

    OPEN p_rows FOR
    SELECT r.reminder_id,
           r.student_id,
           s.student_name,
           s.class_name,
           r.channels_requested,
           r.channels_delivered,
           r.to_email,
           r.to_phone,
           r.outstanding,
           r.status,
           r.sent_at
    FROM core.fee_reminder_log r
    LEFT JOIN core.students s ON s.student_id = r.student_id
    WHERE r.tenant_id = p_tenant_id AND r.school_id = p_school_id
    ORDER BY r.sent_at DESC
    LIMIT p_take;

    OPEN p_stats FOR
    SELECT COUNT(*) FILTER (WHERE r.sent_at::date = CURRENT_DATE
                              AND COALESCE(r.channels_delivered, '') <> '') AS sent_today,
           COUNT(*)                                                          AS total_ever
    FROM core.fee_reminder_log r
    WHERE r.tenant_id = p_tenant_id AND r.school_id = p_school_id;
END;
$procedure$;
