-- ============================================================================
-- "Charge recurring fees from" — per-school policy for mid-session admissions.
--
--  A student joining mid-session (e.g. July in an Apr–Mar session) is billed
--  monthly tuition from the admission month up to the SESSION END month (the
--  real-world norm — pay only for enrolled months). Schools that instead charge
--  the full session regardless of join date set this to 'SessionStart'.
--
--  Values: 'AdmissionMonth' (default) | 'SessionStart'. Read by
--  core.sp_admission_manage when it generates the monthly ledger.
--
-- Target DB: PostgreSQL (educore). Safe to re-run.
-- ============================================================================

-- ── 1. The column moved ─────────────────────────────────────────────────────
-- charge_fees_from was added to core.school_admission_workflow_settings here.
-- It now lives on academic.academic_years instead, because it decides how a
-- whole session is billed and a school-wide value could be changed halfway
-- through one (fee_charge_from_per_year.sql, which also dropped this column).
-- The ADD is gone rather than left: running this file put the dead column
-- straight back.

-- ── The procedure is not defined here any more ─────────────────────────────
--  core.sp_school_admin_admission_workflow_manage used to be re-created at this
--  point, with whatever parameters this migration added. It is now owned by ONE
--  file, **fee_charge_from_per_year.sql**, and only that file defines it.
--
--  Eight files used to define this procedure. Each one was correct on the day it
--  was written and every one of them says "safe to re-run", so running an older
--  one reverted everything the newer ones had added -- silently, with no error.
--  That is not hypothetical: fee_collection_point.sql was still holding a stale
--  copy of the fee head procedure hours after it had been rewritten, and would
--  have undone the whole of it.
--
--  What this file still owns: nothing -- the charge_fees_from column it added has since moved to academic.academic_years (fee_charge_from_per_year.sql) and was dropped from this table.
