-- ============================================================
-- Feature: Forgot Password via OTP (multi-channel)
-- ============================================================
-- A 6-digit OTP is generated by the app, delivered over the enabled channels
-- (email/SMS/WhatsApp), and verified here. We store only the OTP's SHA-256 hash.
--
--   REQUEST        - look up the user by email OR mobile; retire prior unused codes;
--                    store the new OTP hash (10-min expiry); return the user + contacts
--                    so the app knows where to send it.
--   RESET_WITH_OTP - verify the entered OTP for that user and, on success, set the new
--                    password + clear must_change_password. Returns a status:
--                      OK | INVALID | EXPIRED | LOCKED
--                    After 5 wrong tries the code is locked (single active code at a time).
--
-- The table follows the core.* audit-column convention so a fresh DB matches production.
-- ============================================================

CREATE TABLE IF NOT EXISTS core.password_reset_tokens (
    password_reset_token_id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tenant_id   integer NOT NULL,
    user_id     integer NOT NULL,
    school_id   integer,
    token_hash  text NOT NULL,
    expires_at  timestamp without time zone NOT NULL,
    used_at     timestamp without time zone,
    attempts    integer NOT NULL DEFAULT 0,
    created_by  integer NOT NULL,
    created_at  timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by  integer,
    updated_at  timestamp without time zone,
    deleted_by  integer,
    deleted_at  timestamp without time zone,
    is_deleted  boolean NOT NULL DEFAULT false
);

-- For the pre-existing table: make sure the attempt counter exists.
ALTER TABLE core.password_reset_tokens
    ADD COLUMN IF NOT EXISTS attempts integer NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_prt_token_hash ON core.password_reset_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_prt_user       ON core.password_reset_tokens (user_id);

-- Drop earlier link-based signatures so the OTP version below is the only overload.
DROP PROCEDURE IF EXISTS core.sp_password_reset(
    character varying, character varying, text, text, refcursor);
DROP PROCEDURE IF EXISTS core.sp_password_reset(
    character varying, character varying, text, text, character varying, refcursor);

CREATE OR REPLACE PROCEDURE core.sp_password_reset(
    IN p_operation_type character varying,
    IN p_identifier character varying DEFAULT NULL::character varying,
    IN p_otp_hash text DEFAULT NULL::text,
    IN p_password_hash text DEFAULT NULL::text,
    IN p_user_id integer DEFAULT NULL::integer,
    INOUT p_result refcursor DEFAULT NULL::refcursor)
 LANGUAGE plpgsql
AS $procedure$
DECLARE
    v_user_id   integer;
    v_tenant_id integer;
    v_school_id integer;
    v_token_id  integer;
    v_attempts  integer;
    v_match     boolean;
BEGIN

    IF p_operation_type = 'REQUEST' THEN

        SELECT u.user_id, u.tenant_id, u.school_id
        INTO v_user_id, v_tenant_id, v_school_id
        FROM core.users u
        LEFT JOIN core.user_profiles up
            ON up.user_id = u.user_id
           AND up.tenant_id = u.tenant_id
           AND up.is_deleted = FALSE
        WHERE u.is_deleted = FALSE
          AND u.is_active = TRUE
          AND (LOWER(u.email) = LOWER(p_identifier) OR up.phone = p_identifier)
        LIMIT 1;

        IF v_user_id IS NOT NULL THEN
            -- one active code at a time
            UPDATE core.password_reset_tokens
            SET used_at = CURRENT_TIMESTAMP,
                updated_by = v_user_id,
                updated_at = CURRENT_TIMESTAMP
            WHERE user_id = v_user_id
              AND used_at IS NULL
              AND is_deleted = FALSE;

            INSERT INTO core.password_reset_tokens
                (tenant_id, user_id, school_id, token_hash, expires_at, created_by, attempts)
            VALUES
                (v_tenant_id, v_user_id, v_school_id, p_otp_hash,
                 CURRENT_TIMESTAMP + INTERVAL '10 minutes', v_user_id, 0);
        END IF;

        -- Contacts to deliver the OTP to (empty when the identifier matched nobody).
        OPEN p_result FOR
        SELECT
            u.user_id,
            u.email,
            up.phone,
            up.full_name
        FROM core.users u
        LEFT JOIN core.user_profiles up
            ON up.user_id = u.user_id
           AND up.tenant_id = u.tenant_id
           AND up.is_deleted = FALSE
        WHERE u.user_id = COALESCE(v_user_id, -1);

    ELSIF p_operation_type = 'RESET_WITH_OTP' THEN

        SELECT t.password_reset_token_id, t.attempts, (t.token_hash = p_otp_hash)
        INTO v_token_id, v_attempts, v_match
        FROM core.password_reset_tokens t
        WHERE t.user_id = p_user_id
          AND t.used_at IS NULL
          AND t.is_deleted = FALSE
          AND t.expires_at > CURRENT_TIMESTAMP
        ORDER BY t.password_reset_token_id DESC
        LIMIT 1;

        IF v_token_id IS NULL THEN
            OPEN p_result FOR SELECT FALSE AS success, 'EXPIRED'::text AS status;

        ELSIF v_attempts >= 5 THEN
            UPDATE core.password_reset_tokens
            SET used_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
            WHERE password_reset_token_id = v_token_id;
            OPEN p_result FOR SELECT FALSE AS success, 'LOCKED'::text AS status;

        ELSIF v_match THEN
            UPDATE core.users
            SET password_hash = p_password_hash,
                must_change_password = FALSE,
                updated_by = p_user_id,
                updated_at = CURRENT_TIMESTAMP
            WHERE user_id = p_user_id;

            UPDATE core.password_reset_tokens
            SET used_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
            WHERE password_reset_token_id = v_token_id;

            OPEN p_result FOR SELECT TRUE AS success, 'OK'::text AS status;

        ELSE
            UPDATE core.password_reset_tokens
            SET attempts = attempts + 1, updated_at = CURRENT_TIMESTAMP
            WHERE password_reset_token_id = v_token_id;
            OPEN p_result FOR SELECT FALSE AS success, 'INVALID'::text AS status;
        END IF;

    ELSE
        RAISE EXCEPTION 'Invalid operation type: %', p_operation_type;
    END IF;

END;
$procedure$;
