-- ============================================================================
-- GEOGRAPHY MASTER — Country / State / District
--
-- WHY: address "State" and "City" are free-text boxes on every form in the app.
-- core.school_addresses already holds 'UP', 'uttarpradesh', 'Uttar Pradesh',
-- 'delhi', 'Haryana', 'Haryanafff' and 'TEST' for what is really four states,
-- which breaks the state filter on the school list and every state-wise report.
--
-- DESIGN
--   * NOT tenant-scoped. "Maharashtra" is the same for every tenant, so these
--     tables deliberately have no tenant_id / school_id (unlike config.roles or
--     config.boards). Platform-owned reference data, same class as
--     config.date_formats. This is also why GeoService caches on a GLOBAL key
--     instead of AppCache.Key(name, tenantId, schoolId) — do not "fix" that.
--   * Hierarchical, so it does NOT live in config.lookup_value: that table is
--     flat (category/code/label) with no parent link.
--   * District, not city. India has ~4,000 towns but ~800 districts; district is
--     the unit CBSE / state-board / TC forms actually ask for, and the list stays
--     small enough to keep current. City remains free text with district-driven
--     suggestions.
--
-- MAINTENANCE: states create and rename districts (Rajasthan 2023, Assam 2022,
-- AP 2022...). These lists are a starting point, not gospel — they are plain
-- rows and can be INSERTed/renamed without a code change. Re-runnable:
-- every seed is ON CONFLICT DO NOTHING.
-- ============================================================================

-- ── Tables ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS config.countries (
    country_id    integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iso2          char(2)      NOT NULL,
    name          varchar(100) NOT NULL,
    phone_code    varchar(8),
    display_order integer      NOT NULL DEFAULT 0,
    is_active     boolean      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_country_iso2 UNIQUE (iso2)
);

CREATE TABLE IF NOT EXISTS config.states (
    state_id           integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id         integer      NOT NULL REFERENCES config.countries(country_id),
    state_code         varchar(10)  NOT NULL,   -- ISO 3166-2 subdivision code (MH, UP, DL...)
    name               varchar(100) NOT NULL,
    is_union_territory boolean      NOT NULL DEFAULT FALSE,
    display_order      integer      NOT NULL DEFAULT 0,
    is_active          boolean      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_state_code UNIQUE (country_id, state_code)
);

CREATE TABLE IF NOT EXISTS config.districts (
    district_id integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_id    integer      NOT NULL REFERENCES config.states(state_id),
    name        varchar(120) NOT NULL,
    is_active   boolean      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_district_name UNIQUE (state_id, name)
);

CREATE INDEX IF NOT EXISTS ix_states_country   ON config.states (country_id)  WHERE is_active;
CREATE INDEX IF NOT EXISTS ix_districts_state  ON config.districts (state_id) WHERE is_active;

-- ── Countries ──────────────────────────────────────────────────────────────
-- India first (display_order 1); the rest cover the common NRI / expat cases.
INSERT INTO config.countries (iso2, name, phone_code, display_order) VALUES
    ('IN','India','+91',1),
    ('NP','Nepal','+977',2),
    ('BT','Bhutan','+975',3),
    ('BD','Bangladesh','+880',4),
    ('LK','Sri Lanka','+94',5),
    ('AE','United Arab Emirates','+971',6),
    ('SA','Saudi Arabia','+966',7),
    ('QA','Qatar','+974',8),
    ('OM','Oman','+968',9),
    ('KW','Kuwait','+965',10),
    ('SG','Singapore','+65',11),
    ('MY','Malaysia','+60',12),
    ('GB','United Kingdom','+44',13),
    ('US','United States','+1',14),
    ('CA','Canada','+1',15),
    ('AU','Australia','+61',16)
ON CONFLICT ON CONSTRAINT uq_country_iso2 DO NOTHING;

-- ── States + Union Territories of India ────────────────────────────────────
-- display_order: 1-28 states (alphabetical), 101-108 UTs, so UTs always sort
-- last without the UI needing a group column.
INSERT INTO config.states (country_id, state_code, name, is_union_territory, display_order)
SELECT c.country_id, s.code, s.name, s.ut, s.ord
FROM config.countries c
CROSS JOIN (VALUES
    ('AP','Andhra Pradesh',FALSE,1),
    ('AR','Arunachal Pradesh',FALSE,2),
    ('AS','Assam',FALSE,3),
    ('BR','Bihar',FALSE,4),
    ('CT','Chhattisgarh',FALSE,5),
    ('GA','Goa',FALSE,6),
    ('GJ','Gujarat',FALSE,7),
    ('HR','Haryana',FALSE,8),
    ('HP','Himachal Pradesh',FALSE,9),
    ('JH','Jharkhand',FALSE,10),
    ('KA','Karnataka',FALSE,11),
    ('KL','Kerala',FALSE,12),
    ('MP','Madhya Pradesh',FALSE,13),
    ('MH','Maharashtra',FALSE,14),
    ('MN','Manipur',FALSE,15),
    ('ML','Meghalaya',FALSE,16),
    ('MZ','Mizoram',FALSE,17),
    ('NL','Nagaland',FALSE,18),
    ('OR','Odisha',FALSE,19),
    ('PB','Punjab',FALSE,20),
    ('RJ','Rajasthan',FALSE,21),
    ('SK','Sikkim',FALSE,22),
    ('TN','Tamil Nadu',FALSE,23),
    ('TG','Telangana',FALSE,24),
    ('TR','Tripura',FALSE,25),
    ('UP','Uttar Pradesh',FALSE,26),
    ('UT','Uttarakhand',FALSE,27),
    ('WB','West Bengal',FALSE,28),
    ('AN','Andaman and Nicobar Islands',TRUE,101),
    ('CH','Chandigarh',TRUE,102),
    ('DH','Dadra and Nagar Haveli and Daman and Diu',TRUE,103),
    ('DL','Delhi',TRUE,104),
    ('JK','Jammu and Kashmir',TRUE,105),
    ('LA','Ladakh',TRUE,106),
    ('LD','Lakshadweep',TRUE,107),
    ('PY','Puducherry',TRUE,108)
) AS s(code, name, ut, ord)
WHERE c.iso2 = 'IN'
ON CONFLICT ON CONSTRAINT uq_state_code DO NOTHING;

-- ── Districts of India ─────────────────────────────────────────────────────
INSERT INTO config.districts (state_id, name)
SELECT st.state_id, d.name
FROM (VALUES
    -- Andhra Pradesh (26, post-2022 reorganisation)
    ('AP','Alluri Sitharama Raju'),('AP','Anakapalli'),('AP','Ananthapuramu'),('AP','Annamayya'),
    ('AP','Bapatla'),('AP','Chittoor'),('AP','Dr. B.R. Ambedkar Konaseema'),('AP','East Godavari'),
    ('AP','Eluru'),('AP','Guntur'),('AP','Kakinada'),('AP','Krishna'),('AP','Kurnool'),
    ('AP','Nandyal'),('AP','NTR'),('AP','Palnadu'),('AP','Parvathipuram Manyam'),('AP','Prakasam'),
    ('AP','Sri Potti Sriramulu Nellore'),('AP','Sri Sathya Sai'),('AP','Srikakulam'),('AP','Tirupati'),
    ('AP','Visakhapatnam'),('AP','Vizianagaram'),('AP','West Godavari'),('AP','YSR Kadapa'),
    -- Arunachal Pradesh
    ('AR','Anjaw'),('AR','Changlang'),('AR','Dibang Valley'),('AR','East Kameng'),('AR','East Siang'),
    ('AR','Kamle'),('AR','Keyi Panyor'),('AR','Kra Daadi'),('AR','Kurung Kumey'),('AR','Lepa Rada'),
    ('AR','Lohit'),('AR','Longding'),('AR','Lower Dibang Valley'),('AR','Lower Siang'),
    ('AR','Lower Subansiri'),('AR','Namsai'),('AR','Pakke-Kessang'),('AR','Papum Pare'),
    ('AR','Shi Yomi'),('AR','Siang'),('AR','Tawang'),('AR','Tirap'),('AR','Upper Siang'),
    ('AR','Upper Subansiri'),('AR','West Kameng'),('AR','West Siang'),
    -- Assam
    ('AS','Bajali'),('AS','Baksa'),('AS','Barpeta'),('AS','Biswanath'),('AS','Bongaigaon'),
    ('AS','Cachar'),('AS','Charaideo'),('AS','Chirang'),('AS','Darrang'),('AS','Dhemaji'),
    ('AS','Dhubri'),('AS','Dibrugarh'),('AS','Dima Hasao'),('AS','Goalpara'),('AS','Golaghat'),
    ('AS','Hailakandi'),('AS','Hojai'),('AS','Jorhat'),('AS','Kamrup'),('AS','Kamrup Metropolitan'),
    ('AS','Karbi Anglong'),('AS','Karimganj'),('AS','Kokrajhar'),('AS','Lakhimpur'),('AS','Majuli'),
    ('AS','Morigaon'),('AS','Nagaon'),('AS','Nalbari'),('AS','Sivasagar'),('AS','Sonitpur'),
    ('AS','South Salmara-Mankachar'),('AS','Tamulpur'),('AS','Tinsukia'),('AS','Udalguri'),
    ('AS','West Karbi Anglong'),
    -- Bihar
    ('BR','Araria'),('BR','Arwal'),('BR','Aurangabad'),('BR','Banka'),('BR','Begusarai'),
    ('BR','Bhagalpur'),('BR','Bhojpur'),('BR','Buxar'),('BR','Darbhanga'),('BR','East Champaran'),
    ('BR','Gaya'),('BR','Gopalganj'),('BR','Jamui'),('BR','Jehanabad'),('BR','Kaimur'),
    ('BR','Katihar'),('BR','Khagaria'),('BR','Kishanganj'),('BR','Lakhisarai'),('BR','Madhepura'),
    ('BR','Madhubani'),('BR','Munger'),('BR','Muzaffarpur'),('BR','Nalanda'),('BR','Nawada'),
    ('BR','Patna'),('BR','Purnia'),('BR','Rohtas'),('BR','Saharsa'),('BR','Samastipur'),
    ('BR','Saran'),('BR','Sheikhpura'),('BR','Sheohar'),('BR','Sitamarhi'),('BR','Siwan'),
    ('BR','Supaul'),('BR','Vaishali'),('BR','West Champaran'),
    -- Chhattisgarh
    ('CT','Balod'),('CT','Baloda Bazar'),('CT','Balrampur-Ramanujganj'),('CT','Bastar'),
    ('CT','Bemetara'),('CT','Bijapur'),('CT','Bilaspur'),('CT','Dantewada'),('CT','Dhamtari'),
    ('CT','Durg'),('CT','Gariaband'),('CT','Gaurela-Pendra-Marwahi'),('CT','Janjgir-Champa'),
    ('CT','Jashpur'),('CT','Kabirdham'),('CT','Kanker'),('CT','Khairagarh-Chhuikhadan-Gandai'),
    ('CT','Kondagaon'),('CT','Korba'),('CT','Koriya'),('CT','Mahasamund'),
    ('CT','Manendragarh-Chirmiri-Bharatpur'),('CT','Mohla-Manpur-Ambagarh Chowki'),('CT','Mungeli'),
    ('CT','Narayanpur'),('CT','Raigarh'),('CT','Raipur'),('CT','Rajnandgaon'),('CT','Sakti'),
    ('CT','Sarangarh-Bilaigarh'),('CT','Sukma'),('CT','Surajpur'),('CT','Surguja'),
    -- Goa
    ('GA','North Goa'),('GA','South Goa'),
    -- Gujarat
    ('GJ','Ahmedabad'),('GJ','Amreli'),('GJ','Anand'),('GJ','Aravalli'),('GJ','Banaskantha'),
    ('GJ','Bharuch'),('GJ','Bhavnagar'),('GJ','Botad'),('GJ','Chhota Udepur'),('GJ','Dahod'),
    ('GJ','Dang'),('GJ','Devbhoomi Dwarka'),('GJ','Gandhinagar'),('GJ','Gir Somnath'),
    ('GJ','Jamnagar'),('GJ','Junagadh'),('GJ','Kheda'),('GJ','Kutch'),('GJ','Mahisagar'),
    ('GJ','Mehsana'),('GJ','Morbi'),('GJ','Narmada'),('GJ','Navsari'),('GJ','Panchmahal'),
    ('GJ','Patan'),('GJ','Porbandar'),('GJ','Rajkot'),('GJ','Sabarkantha'),('GJ','Surat'),
    ('GJ','Surendranagar'),('GJ','Tapi'),('GJ','Vadodara'),('GJ','Valsad'),
    -- Haryana
    ('HR','Ambala'),('HR','Bhiwani'),('HR','Charkhi Dadri'),('HR','Faridabad'),('HR','Fatehabad'),
    ('HR','Gurugram'),('HR','Hisar'),('HR','Jhajjar'),('HR','Jind'),('HR','Kaithal'),('HR','Karnal'),
    ('HR','Kurukshetra'),('HR','Mahendragarh'),('HR','Nuh'),('HR','Palwal'),('HR','Panchkula'),
    ('HR','Panipat'),('HR','Rewari'),('HR','Rohtak'),('HR','Sirsa'),('HR','Sonipat'),
    ('HR','Yamunanagar'),
    -- Himachal Pradesh
    ('HP','Bilaspur'),('HP','Chamba'),('HP','Hamirpur'),('HP','Kangra'),('HP','Kinnaur'),
    ('HP','Kullu'),('HP','Lahaul and Spiti'),('HP','Mandi'),('HP','Shimla'),('HP','Sirmaur'),
    ('HP','Solan'),('HP','Una'),
    -- Jharkhand
    ('JH','Bokaro'),('JH','Chatra'),('JH','Deoghar'),('JH','Dhanbad'),('JH','Dumka'),
    ('JH','East Singhbhum'),('JH','Garhwa'),('JH','Giridih'),('JH','Godda'),('JH','Gumla'),
    ('JH','Hazaribagh'),('JH','Jamtara'),('JH','Khunti'),('JH','Koderma'),('JH','Latehar'),
    ('JH','Lohardaga'),('JH','Pakur'),('JH','Palamu'),('JH','Ramgarh'),('JH','Ranchi'),
    ('JH','Sahebganj'),('JH','Seraikela-Kharsawan'),('JH','Simdega'),('JH','West Singhbhum'),
    -- Karnataka
    ('KA','Bagalkot'),('KA','Ballari'),('KA','Belagavi'),('KA','Bengaluru Rural'),
    ('KA','Bengaluru Urban'),('KA','Bidar'),('KA','Chamarajanagar'),('KA','Chikkaballapur'),
    ('KA','Chikkamagaluru'),('KA','Chitradurga'),('KA','Dakshina Kannada'),('KA','Davanagere'),
    ('KA','Dharwad'),('KA','Gadag'),('KA','Hassan'),('KA','Haveri'),('KA','Kalaburagi'),
    ('KA','Kodagu'),('KA','Kolar'),('KA','Koppal'),('KA','Mandya'),('KA','Mysuru'),
    ('KA','Raichur'),('KA','Ramanagara'),('KA','Shivamogga'),('KA','Tumakuru'),('KA','Udupi'),
    ('KA','Uttara Kannada'),('KA','Vijayanagara'),('KA','Vijayapura'),('KA','Yadgir'),
    -- Kerala
    ('KL','Alappuzha'),('KL','Ernakulam'),('KL','Idukki'),('KL','Kannur'),('KL','Kasaragod'),
    ('KL','Kollam'),('KL','Kottayam'),('KL','Kozhikode'),('KL','Malappuram'),('KL','Palakkad'),
    ('KL','Pathanamthitta'),('KL','Thiruvananthapuram'),('KL','Thrissur'),('KL','Wayanad'),
    -- Madhya Pradesh
    ('MP','Agar Malwa'),('MP','Alirajpur'),('MP','Anuppur'),('MP','Ashoknagar'),('MP','Balaghat'),
    ('MP','Barwani'),('MP','Betul'),('MP','Bhind'),('MP','Bhopal'),('MP','Burhanpur'),
    ('MP','Chhatarpur'),('MP','Chhindwara'),('MP','Damoh'),('MP','Datia'),('MP','Dewas'),
    ('MP','Dhar'),('MP','Dindori'),('MP','Guna'),('MP','Gwalior'),('MP','Harda'),('MP','Indore'),
    ('MP','Jabalpur'),('MP','Jhabua'),('MP','Katni'),('MP','Khandwa'),('MP','Khargone'),
    ('MP','Maihar'),('MP','Mandla'),('MP','Mandsaur'),('MP','Mauganj'),('MP','Morena'),
    ('MP','Narmadapuram'),('MP','Narsinghpur'),('MP','Neemuch'),('MP','Niwari'),('MP','Pandhurna'),
    ('MP','Panna'),('MP','Raisen'),('MP','Rajgarh'),('MP','Ratlam'),('MP','Rewa'),('MP','Sagar'),
    ('MP','Satna'),('MP','Sehore'),('MP','Seoni'),('MP','Shahdol'),('MP','Shajapur'),
    ('MP','Sheopur'),('MP','Shivpuri'),('MP','Sidhi'),('MP','Singrauli'),('MP','Tikamgarh'),
    ('MP','Ujjain'),('MP','Umaria'),('MP','Vidisha'),
    -- Maharashtra
    ('MH','Ahmednagar'),('MH','Akola'),('MH','Amravati'),('MH','Beed'),('MH','Bhandara'),
    ('MH','Buldhana'),('MH','Chandrapur'),('MH','Chhatrapati Sambhajinagar'),('MH','Dhule'),
    ('MH','Gadchiroli'),('MH','Gondia'),('MH','Hingoli'),('MH','Jalgaon'),('MH','Jalna'),
    ('MH','Kolhapur'),('MH','Latur'),('MH','Mumbai City'),('MH','Mumbai Suburban'),('MH','Nagpur'),
    ('MH','Nanded'),('MH','Nandurbar'),('MH','Nashik'),('MH','Osmanabad'),('MH','Palghar'),
    ('MH','Parbhani'),('MH','Pune'),('MH','Raigad'),('MH','Ratnagiri'),('MH','Sangli'),
    ('MH','Satara'),('MH','Sindhudurg'),('MH','Solapur'),('MH','Thane'),('MH','Wardha'),
    ('MH','Washim'),('MH','Yavatmal'),
    -- Manipur
    ('MN','Bishnupur'),('MN','Chandel'),('MN','Churachandpur'),('MN','Imphal East'),
    ('MN','Imphal West'),('MN','Jiribam'),('MN','Kakching'),('MN','Kamjong'),('MN','Kangpokpi'),
    ('MN','Noney'),('MN','Pherzawl'),('MN','Senapati'),('MN','Tamenglong'),('MN','Tengnoupal'),
    ('MN','Thoubal'),('MN','Ukhrul'),
    -- Meghalaya
    ('ML','East Garo Hills'),('ML','East Jaintia Hills'),('ML','East Khasi Hills'),
    ('ML','Eastern West Khasi Hills'),('ML','North Garo Hills'),('ML','Ri Bhoi'),
    ('ML','South Garo Hills'),('ML','South West Garo Hills'),('ML','South West Khasi Hills'),
    ('ML','West Garo Hills'),('ML','West Jaintia Hills'),('ML','West Khasi Hills'),
    -- Mizoram
    ('MZ','Aizawl'),('MZ','Champhai'),('MZ','Hnahthial'),('MZ','Khawzawl'),('MZ','Kolasib'),
    ('MZ','Lawngtlai'),('MZ','Lunglei'),('MZ','Mamit'),('MZ','Saiha'),('MZ','Saitual'),
    ('MZ','Serchhip'),
    -- Nagaland
    ('NL','Chumoukedima'),('NL','Dimapur'),('NL','Kiphire'),('NL','Kohima'),('NL','Longleng'),
    ('NL','Mokokchung'),('NL','Mon'),('NL','Niuland'),('NL','Noklak'),('NL','Peren'),('NL','Phek'),
    ('NL','Shamator'),('NL','Tseminyu'),('NL','Tuensang'),('NL','Wokha'),('NL','Zunheboto'),
    -- Odisha
    ('OR','Angul'),('OR','Balangir'),('OR','Balasore'),('OR','Bargarh'),('OR','Bhadrak'),
    ('OR','Boudh'),('OR','Cuttack'),('OR','Deogarh'),('OR','Dhenkanal'),('OR','Gajapati'),
    ('OR','Ganjam'),('OR','Jagatsinghpur'),('OR','Jajpur'),('OR','Jharsuguda'),('OR','Kalahandi'),
    ('OR','Kandhamal'),('OR','Kendrapara'),('OR','Kendujhar'),('OR','Khordha'),('OR','Koraput'),
    ('OR','Malkangiri'),('OR','Mayurbhanj'),('OR','Nabarangpur'),('OR','Nayagarh'),('OR','Nuapada'),
    ('OR','Puri'),('OR','Rayagada'),('OR','Sambalpur'),('OR','Subarnapur'),('OR','Sundargarh'),
    -- Punjab
    ('PB','Amritsar'),('PB','Barnala'),('PB','Bathinda'),('PB','Faridkot'),('PB','Fatehgarh Sahib'),
    ('PB','Fazilka'),('PB','Ferozepur'),('PB','Gurdaspur'),('PB','Hoshiarpur'),('PB','Jalandhar'),
    ('PB','Kapurthala'),('PB','Ludhiana'),('PB','Malerkotla'),('PB','Mansa'),('PB','Moga'),
    ('PB','Pathankot'),('PB','Patiala'),('PB','Rupnagar'),('PB','Sahibzada Ajit Singh Nagar'),
    ('PB','Sangrur'),('PB','Shaheed Bhagat Singh Nagar'),('PB','Sri Muktsar Sahib'),
    ('PB','Tarn Taran'),
    -- Rajasthan
    ('RJ','Ajmer'),('RJ','Alwar'),('RJ','Banswara'),('RJ','Baran'),('RJ','Barmer'),
    ('RJ','Bharatpur'),('RJ','Bhilwara'),('RJ','Bikaner'),('RJ','Bundi'),('RJ','Chittorgarh'),
    ('RJ','Churu'),('RJ','Dausa'),('RJ','Dholpur'),('RJ','Dungarpur'),('RJ','Hanumangarh'),
    ('RJ','Jaipur'),('RJ','Jaisalmer'),('RJ','Jalore'),('RJ','Jhalawar'),('RJ','Jhunjhunu'),
    ('RJ','Jodhpur'),('RJ','Karauli'),('RJ','Kota'),('RJ','Nagaur'),('RJ','Pali'),
    ('RJ','Pratapgarh'),('RJ','Rajsamand'),('RJ','Sawai Madhopur'),('RJ','Sikar'),('RJ','Sirohi'),
    ('RJ','Sri Ganganagar'),('RJ','Tonk'),('RJ','Udaipur'),
    -- Sikkim
    ('SK','Gangtok'),('SK','Gyalshing'),('SK','Mangan'),('SK','Namchi'),('SK','Pakyong'),
    ('SK','Soreng'),
    -- Tamil Nadu
    ('TN','Ariyalur'),('TN','Chengalpattu'),('TN','Chennai'),('TN','Coimbatore'),('TN','Cuddalore'),
    ('TN','Dharmapuri'),('TN','Dindigul'),('TN','Erode'),('TN','Kallakurichi'),('TN','Kanchipuram'),
    ('TN','Kanyakumari'),('TN','Karur'),('TN','Krishnagiri'),('TN','Madurai'),('TN','Mayiladuthurai'),
    ('TN','Nagapattinam'),('TN','Namakkal'),('TN','Nilgiris'),('TN','Perambalur'),
    ('TN','Pudukkottai'),('TN','Ramanathapuram'),('TN','Ranipet'),('TN','Salem'),('TN','Sivaganga'),
    ('TN','Tenkasi'),('TN','Thanjavur'),('TN','Theni'),('TN','Thoothukudi'),('TN','Tiruchirappalli'),
    ('TN','Tirunelveli'),('TN','Tirupathur'),('TN','Tiruppur'),('TN','Tiruvallur'),
    ('TN','Tiruvannamalai'),('TN','Tiruvarur'),('TN','Vellore'),('TN','Viluppuram'),
    ('TN','Virudhunagar'),
    -- Telangana
    ('TG','Adilabad'),('TG','Bhadradri Kothagudem'),('TG','Hanumakonda'),('TG','Hyderabad'),
    ('TG','Jagtial'),('TG','Jangaon'),('TG','Jayashankar Bhupalpally'),('TG','Jogulamba Gadwal'),
    ('TG','Kamareddy'),('TG','Karimnagar'),('TG','Khammam'),('TG','Komaram Bheem Asifabad'),
    ('TG','Mahabubabad'),('TG','Mahabubnagar'),('TG','Mancherial'),('TG','Medak'),
    ('TG','Medchal-Malkajgiri'),('TG','Mulugu'),('TG','Nagarkurnool'),('TG','Nalgonda'),
    ('TG','Narayanpet'),('TG','Nirmal'),('TG','Nizamabad'),('TG','Peddapalli'),
    ('TG','Rajanna Sircilla'),('TG','Rangareddy'),('TG','Sangareddy'),('TG','Siddipet'),
    ('TG','Suryapet'),('TG','Vikarabad'),('TG','Wanaparthy'),('TG','Warangal'),
    ('TG','Yadadri Bhuvanagiri'),
    -- Tripura
    ('TR','Dhalai'),('TR','Gomati'),('TR','Khowai'),('TR','North Tripura'),('TR','Sepahijala'),
    ('TR','South Tripura'),('TR','Unakoti'),('TR','West Tripura'),
    -- Uttar Pradesh
    ('UP','Agra'),('UP','Aligarh'),('UP','Ambedkar Nagar'),('UP','Amethi'),('UP','Amroha'),
    ('UP','Auraiya'),('UP','Ayodhya'),('UP','Azamgarh'),('UP','Baghpat'),('UP','Bahraich'),
    ('UP','Ballia'),('UP','Balrampur'),('UP','Banda'),('UP','Barabanki'),('UP','Bareilly'),
    ('UP','Basti'),('UP','Bhadohi'),('UP','Bijnor'),('UP','Budaun'),('UP','Bulandshahr'),
    ('UP','Chandauli'),('UP','Chitrakoot'),('UP','Deoria'),('UP','Etah'),('UP','Etawah'),
    ('UP','Farrukhabad'),('UP','Fatehpur'),('UP','Firozabad'),('UP','Gautam Buddha Nagar'),
    ('UP','Ghaziabad'),('UP','Ghazipur'),('UP','Gonda'),('UP','Gorakhpur'),('UP','Hamirpur'),
    ('UP','Hapur'),('UP','Hardoi'),('UP','Hathras'),('UP','Jalaun'),('UP','Jaunpur'),
    ('UP','Jhansi'),('UP','Kannauj'),('UP','Kanpur Dehat'),('UP','Kanpur Nagar'),('UP','Kasganj'),
    ('UP','Kaushambi'),('UP','Kheri'),('UP','Kushinagar'),('UP','Lalitpur'),('UP','Lucknow'),
    ('UP','Maharajganj'),('UP','Mahoba'),('UP','Mainpuri'),('UP','Mathura'),('UP','Mau'),
    ('UP','Meerut'),('UP','Mirzapur'),('UP','Moradabad'),('UP','Muzaffarnagar'),('UP','Pilibhit'),
    ('UP','Pratapgarh'),('UP','Prayagraj'),('UP','Raebareli'),('UP','Rampur'),('UP','Saharanpur'),
    ('UP','Sambhal'),('UP','Sant Kabir Nagar'),('UP','Shahjahanpur'),('UP','Shamli'),
    ('UP','Shravasti'),('UP','Siddharthnagar'),('UP','Sitapur'),('UP','Sonbhadra'),
    ('UP','Sultanpur'),('UP','Unnao'),('UP','Varanasi'),
    -- Uttarakhand
    ('UT','Almora'),('UT','Bageshwar'),('UT','Chamoli'),('UT','Champawat'),('UT','Dehradun'),
    ('UT','Haridwar'),('UT','Nainital'),('UT','Pauri Garhwal'),('UT','Pithoragarh'),
    ('UT','Rudraprayag'),('UT','Tehri Garhwal'),('UT','Udham Singh Nagar'),('UT','Uttarkashi'),
    -- West Bengal
    ('WB','Alipurduar'),('WB','Bankura'),('WB','Birbhum'),('WB','Cooch Behar'),
    ('WB','Dakshin Dinajpur'),('WB','Darjeeling'),('WB','Hooghly'),('WB','Howrah'),
    ('WB','Jalpaiguri'),('WB','Jhargram'),('WB','Kalimpong'),('WB','Kolkata'),('WB','Malda'),
    ('WB','Murshidabad'),('WB','Nadia'),('WB','North 24 Parganas'),('WB','Paschim Bardhaman'),
    ('WB','Paschim Medinipur'),('WB','Purba Bardhaman'),('WB','Purba Medinipur'),('WB','Purulia'),
    ('WB','South 24 Parganas'),('WB','Uttar Dinajpur'),
    -- Andaman and Nicobar Islands
    ('AN','Nicobar'),('AN','North and Middle Andaman'),('AN','South Andaman'),
    -- Chandigarh
    ('CH','Chandigarh'),
    -- Dadra and Nagar Haveli and Daman and Diu
    ('DH','Dadra and Nagar Haveli'),('DH','Daman'),('DH','Diu'),
    -- Delhi
    ('DL','Central Delhi'),('DL','East Delhi'),('DL','New Delhi'),('DL','North Delhi'),
    ('DL','North East Delhi'),('DL','North West Delhi'),('DL','Shahdara'),('DL','South Delhi'),
    ('DL','South East Delhi'),('DL','South West Delhi'),('DL','West Delhi'),
    -- Jammu and Kashmir
    ('JK','Anantnag'),('JK','Bandipora'),('JK','Baramulla'),('JK','Budgam'),('JK','Doda'),
    ('JK','Ganderbal'),('JK','Jammu'),('JK','Kathua'),('JK','Kishtwar'),('JK','Kulgam'),
    ('JK','Kupwara'),('JK','Poonch'),('JK','Pulwama'),('JK','Rajouri'),('JK','Ramban'),
    ('JK','Reasi'),('JK','Samba'),('JK','Shopian'),('JK','Srinagar'),('JK','Udhampur'),
    -- Ladakh
    ('LA','Kargil'),('LA','Leh'),
    -- Lakshadweep
    ('LD','Lakshadweep'),
    -- Puducherry
    ('PY','Karaikal'),('PY','Mahe'),('PY','Puducherry'),('PY','Yanam')
) AS d(state_code, name)
JOIN config.states st ON st.state_code = d.state_code
JOIN config.countries c ON c.country_id = st.country_id AND c.iso2 = 'IN'
ON CONFLICT ON CONSTRAINT uq_district_name DO NOTHING;

-- ============================================================================
-- Lookup provider. Same parameter shape as config.sp_dropdown_common
-- (p_activity / p_param1 / p_param2 / p_result returning "Name","Code") so the
-- existing IBaseService.GetSelectListAsync maps it with no new plumbing.
--   Country            -> all active countries, India first
--   State   p_param1 = country_id (blank = India)
--   District p_param1 = state_id
-- ============================================================================
CREATE OR REPLACE PROCEDURE config.sp_geo_lookup(
    IN p_activity character varying,
    IN p_param1 character varying DEFAULT NULL::character varying,
    IN p_param2 character varying DEFAULT NULL::character varying,
    INOUT p_result refcursor DEFAULT 'geo_cursor'::refcursor)
 LANGUAGE plpgsql
AS $procedure$
DECLARE
    v_parent integer := CASE WHEN p_param1 ~ '^\d+$' THEN p_param1::int ELSE NULL END;
BEGIN
    IF p_activity = 'Country' THEN

        OPEN p_result FOR
        SELECT name AS "Name", country_id::text AS "Code"
        FROM config.countries
        WHERE is_active
        ORDER BY display_order, name;

    ELSIF p_activity = 'State' THEN

        -- No country passed = India (the overwhelmingly common case).
        OPEN p_result FOR
        SELECT s.name AS "Name", s.state_id::text AS "Code"
        FROM config.states s
        JOIN config.countries c ON c.country_id = s.country_id
        WHERE s.is_active
          AND s.country_id = COALESCE(v_parent, (SELECT country_id FROM config.countries WHERE iso2 = 'IN'))
        ORDER BY s.display_order, s.name;

    ELSIF p_activity = 'District' THEN

        IF v_parent IS NULL THEN
            RAISE EXCEPTION 'State id is required to list districts.';
        END IF;

        OPEN p_result FOR
        SELECT name AS "Name", district_id::text AS "Code"
        FROM config.districts
        WHERE is_active AND state_id = v_parent
        ORDER BY name;

    ELSE
        RAISE EXCEPTION 'Unknown geo activity: %', p_activity;
    END IF;
END;
$procedure$;

-- ============================================================================
-- Adoption in core.school_addresses — ADDITIVE.
-- The existing city / state varchar columns stay and keep being displayed, so
-- legacy rows ('TEST', 'Haryanafff') and every proc/view that reads a.city /
-- a.state keep working untouched. New saves write BOTH the id and the text.
-- ============================================================================
ALTER TABLE core.school_addresses
    ADD COLUMN IF NOT EXISTS country_id  integer REFERENCES config.countries(country_id),
    ADD COLUMN IF NOT EXISTS state_id    integer REFERENCES config.states(state_id),
    ADD COLUMN IF NOT EXISTS district_id integer REFERENCES config.districts(district_id);

-- Backfill the rows whose free text maps cleanly onto a real state. Anything
-- that does not match is left with a NULL state_id and its original text, so it
-- shows up in the "needs cleanup" query below rather than being silently lost.
UPDATE core.school_addresses a
SET state_id   = s.state_id,
    country_id = s.country_id
FROM config.states s
WHERE a.state_id IS NULL
  AND LOWER(TRIM(a.state)) = LOWER(s.name);

UPDATE core.school_addresses a
SET district_id = d.district_id
FROM config.districts d
WHERE a.district_id IS NULL
  AND a.state_id = d.state_id
  AND LOWER(TRIM(COALESCE(a.district, ''))) = LOWER(d.name);

-- Rows still needing a human decision:
--   SELECT school_address_id, state, city FROM core.school_addresses WHERE state_id IS NULL;
