-- ============================================================================
-- Reference-data lookup: single source of truth for the small, configurable
-- enumerated dropdowns that were previously hard-coded (and inconsistent) across
-- views — payment modes, enquiry source/status, exam types, and the fixed system
-- enums (fee cycle, gender).
--
-- Design (hybrid):
--   * Entity masters (Class, Section, Department, Designation, Fee Head) keep
--     their own tables and are served from there.
--   * These small configurable/enum lists live here, ONE generic table keyed by
--     `category`, so a new list = INSERT rows (no schema/proc change).
--   * Platform DEFAULTS are seeded on tenant_id=0/school_id=0. A school may later
--     override a category by inserting its own rows; the proc then prefers those.
--   * is_system = TRUE marks lists the billing/domain logic depends on (FeeCycle,
--     Gender) — shown in dropdowns but not meant to be edited/deleted via any UI.
--
-- code  = the value stored / posted (keep identical to today's hard-coded values
--         so existing rows keep matching).
-- label = the display text.
-- ============================================================================

CREATE TABLE IF NOT EXISTS config.lookup_value (
    lookup_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      integer      NOT NULL,          -- 0 = platform default
    school_id      integer      NOT NULL,          -- 0 = platform default
    category       varchar(50)  NOT NULL,          -- 'PaymentMode', 'EnquirySource', ...
    code           varchar(80)  NOT NULL,          -- stored/posted value
    label          varchar(120) NOT NULL,          -- display text
    display_order  integer      NOT NULL DEFAULT 0,
    is_active      boolean      NOT NULL DEFAULT TRUE,
    is_system      boolean      NOT NULL DEFAULT FALSE,
    is_deleted     boolean      NOT NULL DEFAULT FALSE,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uq_lookup_value UNIQUE (tenant_id, school_id, category, code)
);

CREATE INDEX IF NOT EXISTS ix_lookup_value_lookup
    ON config.lookup_value (category, tenant_id, school_id)
    WHERE is_deleted = FALSE AND is_active = TRUE;

-- ── Platform defaults (tenant 0 / school 0) ────────────────────────────────
-- Re-runnable: ON CONFLICT DO NOTHING keeps existing/overridden rows intact.
INSERT INTO config.lookup_value (tenant_id, school_id, category, code, label, display_order, is_system) VALUES
    -- Payment modes (configurable)
    (0,0,'PaymentMode','Cash','Cash',1,FALSE),
    (0,0,'PaymentMode','UPI','UPI',2,FALSE),
    (0,0,'PaymentMode','Card','Card',3,FALSE),
    (0,0,'PaymentMode','Cheque','Cheque',4,FALSE),
    (0,0,'PaymentMode','Bank Transfer','Bank Transfer',5,FALSE),
    -- Enquiry source (configurable)
    (0,0,'EnquirySource','Website','Website',1,FALSE),
    (0,0,'EnquirySource','Walk-in','Walk-in',2,FALSE),
    (0,0,'EnquirySource','Visit','Campus Visit',3,FALSE),
    (0,0,'EnquirySource','WhatsApp','WhatsApp',4,FALSE),
    (0,0,'EnquirySource','Referral','Referral',5,FALSE),
    -- Enquiry status (configurable)
    (0,0,'EnquiryStatus','New','New',1,FALSE),
    (0,0,'EnquiryStatus','Interested','Interested',2,FALSE),
    (0,0,'EnquiryStatus','Follow-up Pending','Follow-up Pending',3,FALSE),
    (0,0,'EnquiryStatus','Not Interested','Not Interested',4,FALSE),
    (0,0,'EnquiryStatus','Converted','Converted',5,FALSE),
    -- Exam types (configurable)
    (0,0,'ExamType','unit1','Unit Test 1',1,FALSE),
    (0,0,'ExamType','mid','Mid Term',2,FALSE),
    (0,0,'ExamType','final','Final',3,FALSE),
    (0,0,'ExamType','annual','Annual',4,FALSE),
    -- Fee cycle (SYSTEM — billing engine depends on these exact codes)
    (0,0,'FeeCycle','One Time','One Time',1,TRUE),
    (0,0,'FeeCycle','Monthly','Monthly',2,TRUE),
    (0,0,'FeeCycle','Quarterly','Quarterly',3,TRUE),
    (0,0,'FeeCycle','Yearly','Yearly',4,TRUE),
    -- Gender (SYSTEM — universal)
    (0,0,'Gender','Male','Male',1,TRUE),
    (0,0,'Gender','Female','Female',2,TRUE),
    (0,0,'Gender','Other','Other',3,TRUE)
ON CONFLICT ON CONSTRAINT uq_lookup_value DO NOTHING;

-- ============================================================================
-- Extend the shared dropdown provider. Entity-master branches (Class,
-- AcademicYear) are unchanged; every OTHER activity now resolves generically
-- from config.lookup_value, so new lists need no proc change.
--   p_param1 = tenantId, p_param2 = schoolId (used only by the generic branch).
-- ============================================================================
CREATE OR REPLACE PROCEDURE config.sp_dropdown_common(
    IN p_activity character varying,
    IN p_param1 character varying DEFAULT NULL::character varying,
    IN p_param2 character varying DEFAULT NULL::character varying,
    INOUT p_result refcursor DEFAULT 'result_cursor'::refcursor)
  LANGUAGE plpgsql
AS $procedure$
DECLARE
    v_tenant integer := CASE WHEN p_param1 ~ '^\d+$' THEN p_param1::int ELSE NULL END;
    v_school integer := CASE WHEN p_param2 ~ '^\d+$' THEN p_param2::int ELSE NULL END;
BEGIN
    IF p_activity = 'AcademicYear' THEN

        OPEN p_result FOR
        SELECT
            academic_year_name AS "Name",
            academic_year_id::text AS "Code",
            COALESCE(is_current, FALSE) AS "IsSelected"
        FROM academic.academic_years
        WHERE COALESCE(is_deleted, FALSE) = FALSE
          AND COALESCE(is_active, TRUE) = TRUE
          AND tenant_id = v_tenant AND school_id = v_school   -- multi-tenant scope
        ORDER BY COALESCE(is_current, FALSE) DESC, academic_year_id DESC;

    ELSIF p_activity = 'Class' THEN

        OPEN p_result FOR
        SELECT
            class_name AS "Name",
            academic_class_id::text AS "Code"
        FROM academic.academic_classes
        WHERE COALESCE(is_deleted, FALSE) = FALSE
          AND COALESCE(is_active, TRUE) = TRUE
          AND tenant_id = v_tenant AND school_id = v_school   -- multi-tenant scope
        ORDER BY academic_class_id DESC;

    ELSE
        -- Generic reference lists. Prefer the school's own rows for this
        -- category; if it has none, fall back to platform defaults (0/0).
        OPEN p_result FOR
        SELECT q."Name", q."Code"
        FROM (
            SELECT label AS "Name", code AS "Code", display_order AS ord
            FROM config.lookup_value
            WHERE category = p_activity AND is_active AND NOT is_deleted
              AND tenant_id = COALESCE(v_tenant, -1)
              AND school_id = COALESCE(v_school, -1)
            UNION ALL
            SELECT g.label, g.code, g.display_order
            FROM config.lookup_value g
            WHERE g.category = p_activity AND g.is_active AND NOT g.is_deleted
              AND g.tenant_id = 0 AND g.school_id = 0
              AND NOT EXISTS (
                  SELECT 1 FROM config.lookup_value s
                  WHERE s.category = p_activity AND s.is_active AND NOT s.is_deleted
                    AND s.tenant_id = COALESCE(v_tenant, -1)
                    AND s.school_id = COALESCE(v_school, -1))
        ) q
        ORDER BY q.ord, q."Name";

    END IF;
END;
$procedure$;
