-- ============================================================================
-- Remove fee amounts from Admission Workflow Settings
--  Fee amounts (registration fee, security deposit) are now master data defined
--  as Fee Heads (School Settings → Fee Head, Collection Point = Registration /
--  Admission). The workflow settings keep only process toggles. This proc drops
--  the two amount parameters and stops writing the amount columns.
--
--  The registration_fee_amount / security_fee_amount columns are intentionally
--  LEFT IN PLACE (unused) to avoid a destructive migration; a later cleanup may
--  drop them once nothing reads them.
--
-- Target DB: PostgreSQL (educore). Safe to re-run.
-- ============================================================================

-- ── The procedure is not defined here any more ─────────────────────────────
--  core.sp_school_admin_admission_workflow_manage used to be re-created at this
--  point, with whatever parameters this migration added. It is now owned by ONE
--  file, **fee_charge_from_per_year.sql**, and only that file defines it.
--
--  Eight files used to define this procedure. Each one was correct on the day it
--  was written and every one of them says "safe to re-run", so running an older
--  one reverted everything the newer ones had added -- silently, with no error.
--  That is not hypothetical: fee_collection_point.sql was still holding a stale
--  copy of the fee head procedure hours after it had been rewritten, and would
--  have undone the whole of it.
--
--  What this file still owns: nothing but this note -- its whole job was the procedure, which dropped the two numeric fee amounts in favour of Fee Heads. The columns themselves were dropped later, in workflow_drop_dead_amount_columns.sql.
